### ISSUE TITLE
"niak_brick_cmp_files" cannot deal with non gzip mnc files

### ISSUE THREAD

**Issue by poquirion** [SIMEXP/niak#215]
It prevents the niak_test_all to be completed

Here are the non gz files

anat/subject2/transf_subject2_nativefunc_to_stereonl_grid_0.mnc
anat/subject1/transf_subject1_stereolin_to_stereonl_grid.mnc
anat/subject2/transf_subject2_nativefunc_to_stereonl_grid_0.mnc
anat/subject2/transf_subject2_stereolin_to_stereonl_grid.mnc

**Comment by poquirion** [comment]
well it seems that it is not the source of the error in niak_test_all but is still print `Error reading file.` when I read these files... But seems to have no other effect.

**Comment by pbellec** [comment]
So the niak reader/writer for minc only work for structural or functional MRI data. It does not read arbitrary minc files. The files you are mentioning are 4D, but the fourth dimension is not time (they are transformation fields), which crashes niak's reader. It's an issue that has surfaced from time to time, as some people use these reader and writer for various purposes, independently of what niak offers in terms of pipelines. I started a project called mominc. It's a clean netcdf/hdf5 based reader/writer for minc, which would be a tad bit faster than what we have and work on any minc file. Because the added benefits are small for what we do, I've never taken the time to finish it.
