### ISSUE TITLE
Can reproduce travis `basc_test_stability_rest_demoniak` failure

### ISSUE THREAD

**Issue by poquirion** [SIMEXP/niak#219]
On my ubuntu using docker on my 16.04 platform.

**Comment by pbellec** [comment]
Very weird. Restarting the test on travis to check what is going on. We need those TRAVIS logs ...

**Comment by poquirion** [comment]
I will do some test before, but I propose that we migrate to https://circleci.com/. It seems that they keep the output files. We tested with that tool at the Palo Alto workshop.

**Comment by pbellec** [comment]
OK great.

**Comment by poquirion** [comment]
Got the travis test with logs of the error [here](https://travis-ci.org/SIMEXP/niak/builds/150829376).

**Comment by poquirion** [comment]
Niak on circle ci

https://circleci.com/gh/SIMEXP/niak

**Comment by poquirion** [comment]
!#@$!
https://travis-ci.org/SIMEXP/niak

Travis and Circle do not even agree on where to fail!

**Comment by poquirion** [comment]
OK, new plan, I am going to do the release computation and release of the target on circleci. This way we will be able to reproduce every time. I just have to port the release tool so it is fully automatic. Would that make be ok?

**Comment by pbellec** [comment]
OK with that plan, at least we'll have consistent results. But in the past, using docker we were able to reproduce results across a wide range of systems. We need to understand why this is not the case anymore. Are we now compiling the MINC tools instead of fetching binaries? we may want to look into compilation flags with Vlad. 

I also take out from this that we need to implement experiments to quantify differences across systems, and take measures to reduce these. I see this as high priority, we need to discuss with Tristan asap. 

Re BASC, in the absence of logs it's not possible to find out.

**Comment by pbellec** [comment]
Done.
