### ISSUE TITLE
make preprocessing setup faster

### ISSUE THREAD

**Issue by poquirion** [SIMEXP/niak#289]
The biggest time consumption is loading gb_vars!

Kind of relate to https://github.com/SIMEXP/psom/issues/111

**Comment by pbellec** [comment]
OK so I gave it a bit of thought. First I agree this is a priority. NIAK's primary mission is to process large datasets fast and reliably. Having a long overhead to set up a pipeline goes against that primary mission.

In terms of implementation, here is what I am thinking. I am going to change niak_gb_vars from a script to a function, that generate a global variable gb_niak. If the variable does not exist, it will create it, otherwise just send back the variable. I may miss something, but I expect that the variable will be created by the first call, and that any subsequent call from the same matlab session will just send back the same variable, thus removing any overhead. I'll experiment a bit to see if that works.

**Comment by pbellec** [comment]
Just to finish the tought, if that work I would only need to make a massive search and replace "niak_gb_vars" by "niak_gb = niak_gb_vars", and "niak_gb_" by "niak_gb." and every niak brick should be compliant with the new mechanism.

**Comment by poquirion** [comment]
My approach is to add a loop that make all gb_ varable global at the end of niak_gb_var and put an if at its stats that return is the variable gb_niak_var_gb is true

**Comment by pbellec** [comment]
I think it should work. I find having one `gb_niak` variable more elegant, but with your approach you won't need to change the niak code base, so that's better.

**Comment by poquirion** [comment]
seems that my approach does not work since you have to explicitly load the the global variable by name in every function where they are used.

**Comment by pbellec** [comment]
mmmhhh yes indeed

**Comment by poquirion** [comment]
I when your way more of less. 

I just defined at global struct called `GB_NIAK` that is called at the top of `niak_gb_vars.`

Then replaced (429 occurence) `gb_niak_something` to `GB_NIAK.something`, so we know that `GB_NIAK` is global, I also omitted the replacement of  `gb_niak_omitted`!

**Comment by pbellec** [comment]
great job about `gb_niak_omitted`, did not think about that one. Quick comments: 
 * not sure if you actually used `GB_NIAK` and not `gb_niak`. For relatively obscure reasones, niak does not use capital letters in variable names. Would be better to have `gb_niak`. If too complicated, no problem.

**Comment by pbellec** [comment]
* In early attempts to speed up the process, I had introduced a flag `flag_gb_niak_fast_gb` to only initialize a limited number of variables. For this reason there are lines "flag_gb_niak_fast_gb = true;" in a number of scripts. Those are now deprecated and can be suppressed.

**Comment by pbellec** [comment]
finally, curious to see if that change actually generates a speed up.

**Comment by poquirion** [comment]
Do you have other global variable in the code. I think using a global one here would be in line with traditions (I am a real conservative)

**Comment by poquirion** [comment]
Adding subject is about twice as fast on my machine.

**Comment by pbellec** [comment]
would be worth profiling again to check if there is still room for improvement

**Comment by poquirion** [comment]
Implemeted in 0.18.0
