### ISSUE TITLE
regress_confounds failure

### ISSUE THREAD

**Issue by nooralsh** [SIMEXP/niak#382]
Hello!

We ran niak on 3 subsets of data, one of which was a special case of "flipped" images in which our rsfMRI vols had alternatingly-oriented (ie AP, PA, AP, PA, ...) volumes. We sorted out this flipping issue using FSL's `topup` on their field maps and correcting the main volumes. To achieve this, we split the volumes into two 4D volumes of _only_ PA or AP volumes and decided to keep them separated when running niak. Therefore, each subject run through niak had two sessions, a *_PA and a *_AP volume.

Nothing was different between the niak scripts of the flipped and other two subsets (siemens vs not_siemens). The other two subsets ran with few failures but the "flipped" set had one consistent failure at the regress_counfounds step. For example:  
```

**************************************************************************
  Log file of job regress_confounds_P1480_session1_restPA (status failed) 
**************************************************************************


******************************
Log of the (octave) job : regress_confounds_P1480_session1_restPA
Started on 03-Oct-2018 19:06:33
User: nooralsh
host : gra799
system : unix
******************************
Reading the fMRI dataset ...
/home/nooralsh/scratch/niak/flippedfmri_preprocess/resample/fmri_P1480_session1_restPA_n.nii.gz
Reading the confounds...
/home/nooralsh/scratch/niak/flippedfmri_preprocess/resample/fmri_P1480_session1_restPA_n_confounds.tsv.gz
Scrubbing frames exhibiting large motion ...
Adding slow time drifts ...
Ignoring high frequency noise...
Adding high frequency noise...
Adding white matter average...
Adding ventricular average...
Adding global signal...
Ignoring COMPCOR...
Regressing the confounds...
    Total number of confounds: 50
    Total number of time points for regression: 47
warning: matrix singular to machine precision, rcond = nan
warning: matrix singular to machine precision


Something went bad ... the job has FAILED !
The last error message occured was :
operator *: nonconformant arguments (op1 is 10x10, op2 is 47x176384)
File /usr/local/niak/commands/statistics/niak_glm.m at line 161
File /usr/local/niak/bricks/fmri_preprocess/niak_brick_regress_confounds.m at line 328
File /usr/local/niak/extensions/psom-2.3.1/psom_run_job.m at line 185
File /usr/local/niak/extensions/psom-2.3.1/psom_run_job.m at line 106
File /usr/local/niak/extensions/psom-2.3.1/psom_worker.m at line 161


The output file or directory /home/nooralsh/scratch/niak/flippedfmri_preprocess/intermediate/P1480/regress_confounds/fmri_P1480_session1_restPA_cor.nii.gz has not been generated!
The output file or directory /home/nooralsh/scratch/niak/flippedfmri_preprocess/intermediate/P1480/regress_confounds/scrubbing_P1480_session1_restPA.mat has not been generated!

**********************************************
03-Oct-2018 19:06:35 : The job has FAILED
Total time used to process the job : 1.59 sec.
**********************************************
```
We broke down the regress_confounds step line by line to determine the cause of the issue at line 161 in `niak_glm.m`: `beta = (x'*x)\x'*y;`. 

We compared this step between a successful subject and a failed subject and found the only difference to be at line 322 in `niak_brick_regress_confounds.m`: `x2 = (x2-repmat(x2_mean,[size(x2,1),1]))./repmat(x2_std,[size(x2,1) 1]);`. 

The failed subject's `x2` included many 0s which were not present in the image before this step and were not in the successful subject's matrix. We think this was caused by a division error in MATLAB but were unable to remedy the problem. 

Any suggestions welcome, thanks!

**Comment by pbellec** [comment]
Hi @nooralsh 

It's been a while I've wanted to make that warning more explicit.

It means that the brain mask is empty, likely because the registration failed.
  Check the volumes in the `anat` folder.

This may be related to the raw data.
  You may want to check that the raw bold and T1 scan are roughly registered.

**Comment by pbellec** [comment]
Sorry, I went too fast through your logs.

It is a common step to have problems, and I jumped to the most common error. 

The issue is indicated at these lines:
```
Regressing the confounds...
    Total number of confounds: 50
    Total number of time points for regression: 47
```
Seems like there are less than 50 volumes in these time series, and 50 confounds were selected. 
That's why it's crashing.

Is it normal for these time series to be that short?

**Comment by pbellec** [comment]
Is pasting the original data back into one long time series after flipping them? This way you will have a more typical number of time points.

Otherwise, could you try
```
% Apply regression of motion parameters (true/false)
opt.regress_confounds.flag_motion_params = false;
```
Truth is those parameters eat degrees of freedom without doing much, especially since you are doing a global signal regression.

I am still surprised you have so many confounds (50!), it doesn't make sense. You may want to check you properly coded the TR in your acquisitions (e.g. look at the slice timing logs, or directly in the raw nifti). If this parameter is not correct, this will completely break the high pass filtering.

**Comment by nooralsh** [comment]
Thanks for the tip @pbellec -- we hadn't set the TR properly as niak was pulling the TR from the nifti file which was incorrect. Once we adjusted that, the `regress_confounds` issue seems to have been resolved.

We decided not to re-concatenate the volumes into one as we were concerned that the volumes, having been preprocessed through FSL separately, might appear to have too much "motion" between neighbouring, oppositely-encoded volumes. This was especially so as we wanted to make sure each volume was placed back in the same time order as they had been in the original volume.

For now, this seems to have works! Thanks for your insight & advice.
