### ISSUE TITLE
simplify niak_brick_scores_fmri

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/niak#47]
A couple suggestions, more to come: 
  * the input format is not properly documented. But it doesn't matter. I suggest only supporting cell of strings in the brick, and only the structure fmri.(subject).(session).(run) in the pipeline. The mapping between the two will occur in the pipeline. 
  * I would get rid of the .mat option. First the outputs are not properly documented. Second it makes things way too complicated. I will incorporate the remapping of 4D volumes into .mat files as part of the subtype analysis. 
  * the checks lines 171 to 182 are ugly and very error prone. In any case I don't think it is necessary to get a warning for that. I suggest removing them altogether. 
  * the if statement line 306 is redundant with lines 307 & 317. Please remove. There is a series of similar if statement. 
  * Overall the code is too long. consider making sub-functions.

**Comment by surchs** [comment]
Ok, since I still manage to close issues through a commit, I'll do the manual thing here.
I think we addressed all these issues:
- the brick only supports cells of strings
- the pipeline only supports the input structure
- the brick no longer generates .mat files (except for the extra.mat) and also doesn't have flags for it (or the volume option)
- I removed the checks in line 171 to 182 as they are also no longer necessary
- if statements at the end are gone
- all of this made the brick shorter.
