### ISSUE TITLE
niak QC fmri preprocess

### ISSUE THREAD

**Issue by yassinebha** [SIMEXP/niak#95]
some features to add to the qc function:
*  Add option to review (re-QC) only failed or maybe or ok subjects 
*  Allow QC even the pipeline is not completed
* Allow selection of functional or structural QC only in the options

**Comment by pbellec** [comment]
we should also think about a way to make it easy to exctract what is needed for qc. Currently the files are spread over many folders, which contain other large images.

**Comment by illdopejake** [comment]
Latest QC is excellent and much improved :-)
Some things I noticed that could make it even better (at least for me)
* The contrast on the anatomical image always starts out two dark and I adjust it every time. It would be cool to have it start out a bit brighter.
* Similarly, I find myself modifying the "fade" of the overlay every time. When the program opens, the overlay is set to be 50% each image. I always find myself bring it toward the left, so its about 75% anatomical(pane 2) and 25% from pane 1. This is because the image in Pane 1 default color scale is a heat map, which is much brighter, and thus much more visible in the overlay
* It would be cool if there was a keyboard shortcut to Quit. (Maybe there is and I just don't know about it?)

Great work making this process as painless as possible!

**Comment by pbellec** [comment]
@yassinebha there are multiple issues mixed up here. I will close it and create a new milestone "quality control" with individual issues.
